import { Chapter } from "./types";

export const INITIAL_CHAPTERS: Chapter[] = [
  {
    id: "chapter-1",
    number: 1,
    title: "Gema Talbiyah di Ujung Mimpi",
    subtitle: "Sebuah Awal Dari Kerinduan Panjang",
    isLocked: true,
    summary: "Kisah tentang diterimanya surat undangan berhaji setelah penantian dua belas tahun yang penuh air mata dan doa.",
    imageUrl: "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=80",
    pages: [
      `Gerimis tipis mengguyur kota sore itu. Di balik jendela kaca yang buram oleh embun, aku menatap lalu lalang kendaraan dengan pikiran melayang jauh. Di genggamanku, sebuah amplop berwarna hijau tua berlogo Kementerian Agama terasa begitu hangat—atau mungkin, tangankulah yang gemetar menahan letupan emosi yang membuncah di dalam dada.\n\nDua belas tahun. Bukan waktu yang singkat bagi seorang guru mengaji di pinggiran kota untuk menyisihkan lembar demi lembar rupiah. Setiap malam setelah meluruskan punggung yang lelah, aku dan istriku selalu menatap celengan tanah liat berbentuk Ka'bah kecil di sudut lemari. Kami tahu, secara logika manusia, angka-angka itu mustahil membawa kami melintasi samudera menuju Baitullah. Namun, di atas sajadah, kami memiliki keyakinan yang melampaui logika.\n\n"Panggilan itu bukan untuk mereka yang mampu, tetapi bagi mereka yang dipanggil oleh-Nya," bisik istriku malam itu, menyeka air mata yang menetes di pipinya yang mulai berkerut. Kalimat itu menjadi bahan bakar utama yang menjaga api harapan kami tetap menyala sepanjang malam-malam sepi penuh tengadah doa.`,
      `Hari ini, jawaban dari penantian panjang itu berada di genggamanku. Surat penetapan keberangkatan jamaah haji tahun ini mencantumkan nama kami berdua. Tubuhku luruh seketika di atas lantai ubin yang dingin. Sujud syukur kami lakukan bersama, begitu lama, hingga ubin itu terasa hangat oleh tetesan air mata kebahagiaan yang tak lagi bisa dibendung.\n\nKeesokan harinya, persiapan pun dimulai. Sebagai seorang programmer web yang merangkap penulis novel amatir, aku memutuskan untuk mencatat setiap detak spiritual perjalanan ini. Aku ingin setiap kata yang tertulis di lembaran-lembaran ini menjadi saksi bisu bagaimana sepasang hamba biasa diundang oleh Raja Diraja alam semesta.\n\nKami mulai berlatih berjalan kaki setiap subuh, mengelilingi komplek perumahan demi mempersiapkan fisik. Istriku dengan telaten menghafal doa-doa manasik, sementara aku mengemas laptop kecilku. Aku berjanji pada diriku sendiri, di sela-sela ibadah nanti, jemariku akan merajut kisah ini menjadi baris-baris kalimat yang bisa dibaca oleh anak cucu kami—sebuah memoar cinta menuju tanah suci Mekah.`,
      `Malam terakhir sebelum keberangkatan, rumah kami dipenuhi tetangga dan kerabat yang datang untuk melepas kami dengan doa. Suasana haru begitu kental tercium bersama aroma dupa dan sajadah baru. Semua orang menitipkan doa; ada yang meminta kesembuhan dari penyakitnya, ada yang memohon agar dimudahkan mendapat keturunan, dan ada pula yang sekadar menangis merindukan tanah suci.\n\nAku mencatat semua nama dan doa itu di selembar kertas putih yang kulipat rapi di dalam saku pasporku. Aku tahu, aku membawa harapan banyak jiwa di pundakku.\n\nSaat fajar menyingsing keesokan harinya, bus jemputan kloter kami pun tiba. Diiringi lambaian tangan sanak saudara dan kumandang adzan yang menggetarkan dada, kami melangkah pergi. Air mata perpisahan berpadu dengan binar ketidaksabaran. Kami pergi bukan untuk berlibur, melainkan untuk berserah diri secara total. "Labbaykallahumma labbayk..." gema talbiyah mulai terdengar lamat-lamat dari speaker bus, merambat masuk ke sela-sela sanubari, menandai awal dari perjalanan yang akan mengubah hidup kami selamanya.`
    ]
  },
  {
    id: "chapter-2",
    number: 2,
    title: "Jejak Kaki Pertama di Haramain",
    subtitle: "Menatap Langit Madinah dan Mekah",
    isLocked: true,
    summary: "Momen magis ketika pertama kali menginjakkan kaki di Masjid Nabawi, disambut kehangatan kota Madinah sebelum menempuh perjalanan miqat.",
    imageUrl: "https://images.unsplash.com/photo-1564769625905-50e9ad6319f4?auto=format&fit=crop&w=1200&q=80",
    pages: [
      `Udara gurun yang kering dan panas langsung menerpa wajah kami begitu pintu pesawat terbuka di Bandara Prince Mohammad bin Abdulaziz, Madinah. Namun anehnya, tidak ada rasa gerah yang mengganggu. Yang ada hanyalah rasa takjub yang membuat tenggorokan tersumbat oleh haru. Kami telah sampai di tanah tempat sang kekasih Allah, Rasulullah Muhammad SAW, memijakkan kaki dan membangun peradaban cahaya.\n\nMadinah menyambut kami dengan keteduhan yang magis. Di sepanjang jalan menuju hotel, pohon-pohon kurma berdiri kokoh seolah mengucapkan selamat datang kepada para tamu Allah. Setelah meletakkan barang bawaan seadanya, kami langsung bergegas menuju Masjid Nabawi. Kubah hijau yang legendaris itu tampak anggun di kejauhan, berkilau di bawah siraman cahaya lampu kota.\n\nSaat pertama kali melangkah masuk melewati pelataran masjid yang luas dengan payung-payung raksasa yang mengembang indah, air mataku menetes tanpa sadar. Di sinilah beliau dimakamkan. Di balik pilar-pilar indah ini, jutaan sholawat bergaung melintasi zaman.`,
      `Selama delapan hari di Madinah, kami tenggelam dalam rutinitas ibadah yang menenangkan jiwa. Setiap menjelang waktu shalat, pelataran Nabawi berubah menjadi lautan manusia dari berbagai penjuru dunia. Berkulit putih, hitam, cokelat, semua melebur dalam saf-saf yang rapat tanpa sekat kasta sosial. Di sini, aku merasa betapa kecilnya diriku, hanya sebutir debu di tengah samudera umat Islam.\n\nMomen paling mengharukan adalah saat kami berkesempatan mengunjungi Raudhah—taman surga yang terletak di antara mimbar dan makam Rasulullah. Berdesak-desakan dengan ribuan jamaah lain, di bawah penjagaan ketat para askar, aku bersujud di atas karpet hijau yang mulia itu. Di tempat yang mustajab ini, aku tumpahkan seluruh isi kertas doa titipan kerabat. Dadaku terguncang hebat membayangkan betapa dekatnya posisiku dengan jasad mulia sang Nabi.\n\n"Ya Rasulullah, kami datang membawa rindu..." bisikku lirih di sela-sela isak tangis yang tertahan.`,
      `Hari kesembilan tiba, menandai akhir masa tinggal kami di Madinah. Kini saatnya kami menuju tujuan utama: Mekah al-Mukarramah. Kami mengenakan pakaian ihram dari hotel—dua lembar kain putih tak berjahit bagi laki-laki, melambangkan kesetaraan mutlak di hadapan sang Pencipta. Tidak ada lagi saku, tidak ada lagi merek pakaian, tidak ada lagi pangkat.\n\nKami mengambil miqat dan mengikrarkan niat umrah di Masjid Bir Ali. Sejak detik itu, larangan-larangan ihram berlaku. Pikiran harus dijaga dari kemarahan, lisan harus dibersihkan dari kata-kata sia-sia, dan hati harus sepenuhnya terpaut pada Baitullah.\n\nBus bergerak membelah malam gurun pasir menuju Mekah. Di dalam kegelapan, kumandang Talbiyah bersahut-sahutan dari mulut para jamaah yang gemetar menahan debar jantung. Mekah, kota suci yang selama ini hanya kami lihat gambarnya di sajadah dan layar kaca, kini hanya berjarak beberapa jam perjalanan saja. Jantungku berdegup kencang, membayangkan momen magis tatapan pertama pada Ka'bah.`
    ]
  },
  {
    id: "chapter-3",
    number: 3,
    title: "Thawaf: Wadah Air Mata",
    subtitle: "Pelukan Pertama Pada Ka'bah",
    isLocked: true,
    summary: "Bab Eksklusif mengenai tatapan mata pertama kali menghadap Kakbah, berserah dalam pusaran Thawaf yang menggetarkan sukma.",
    imageUrl: "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?auto=format&fit=crop&w=1200&q=80",
    pages: [
      `Bus kami tiba di Mekah menjelang tengah malam. Kelelahan fisik akibat perjalanan jauh seketika sirna digantikan oleh ketegangan spiritual yang luar biasa. Setelah merapikan barang-barang di kamar maktab, kami berjalan kaki menuju Masjidil Haram. Di bawah siraman lampu-lampu megah, gerbang-gerbang raksasa masjid tampak menjulang tinggi seolah menyambut kami dengan pelukan hangat.\n\nKami melangkah masuk melalui Babus Salam dengan kaki kanan terlebih dahulu, melafalkan doa masuk masjid dengan bibir gemetar. Mataku sengaja kutundukkan ke lantai ubin marmer putih yang dingin, menahan diri untuk tidak langsung mendongak sebelum benar-benar berada di area mataf (tempat thawaf).\n\nLalu, momen itu pun tiba. \n\nKetika aku mengangkat pandanganku, di tengah-tengah pelataran marmer yang sangat luas itu, berdiri sebuah bangunan kubus berselimut kain beludru hitam pekat berhias kaligrafi benang emas yang berkilauan. Ka'bah. Rumah kuno yang dibangun oleh Ibrahim AS dan Ismail AS. Kiblat dari seluruh shalatku sepanjang hidup.`,
      `Lututku terasa lemas seketika. Aku jatuh berlutut di atas marmer dingin itu, menyembunyikan wajahku dengan kedua belah telapak tangan, menangis sejadi-jadinya. Istriku di sampingku terisak begitu keras hingga pundaknya terguncang hebat. Gambar yang selama puluhan tahun kami pandang di dinding rumah, kini tegak berdiri kokoh hanya beberapa puluh meter di depan mata kami. Sungguh, keindahan aslinya melumpuhkan segala imajinasi.\n\nKami bangkit dan mulai melangkah masuk ke dalam pusaran Thawaf—tujuh putaran berlawanan arah jarum jam. Berada di dalam aliran manusia yang tak pernah berhenti itu terasa seperti berada di dalam galaksi spiritual. Kami berputar, melebur dalam doa-doa yang dipanjatkan dalam berbagai bahasa manusia.\n\nSetiap kali melewati sudut Hajar Aswad, kami melambaikan tangan kanan seraya berteriak lirih, "Bismillahi Allahu Akbar!" Di putaran kelima, pusaran membawa kami begitu dekat dengan dinding Ka'bah. Aku berhasil menyentuh kain kiswahnya yang wangi. Permukaannya terasa kasar namun memberikan ketenangan yang tak terlukiskan bagi jemariku yang lelah.`,
      `Setelah menyelesaikan tujuh putaran Thawaf, kami melaksanakan shalat sunnah dua rakaat di belakang Maqam Ibrahim. Air mata terus mengalir membasahi sajadah, membawa serta segala beban hidup, dosa-dosa masa lalu, dan kepedihan batin yang selama ini terpendam di sudut hati yang paling sunyi. Di sini, semua ego runtuh.\n\nKami kemudian melanjutkan ibadah dengan melaksanakan Sa'i, berjalan dan berlari-lari kecil antara bukit Shofa dan Marwah sebanyak tujuh kali. Mengenang perjuangan ibunda Hajar yang berlari mencari air demi bayinya, Ismail, di tengah gurun yang gersang. \n\nPerjalanan bolak-balik itu mengajariku satu hal penting tentang kehidupan: tugas manusia hanyalah berikhtiar sekuat tenaga berjalan di antara Shofa dan Marwah kehidupan, sementara urusan air zam-zam mukjizat adalah hak prerogatif Allah untuk memunculkannya dari arah yang tak disangka-sangka.`
    ]
  },
  {
    id: "chapter-4",
    number: 4,
    title: "Arafah: Detak Sunyi Padang Pengampunan",
    subtitle: "Ketika Langit Dunia Mendekat",
    isLocked: true,
    summary: "Bab Eksklusif tentang detik-detik menegangkan dan penuh khidmat saat melaksanakan wukuf di padang Arafah, puncak dari ibadah haji.",
    imageUrl: "https://images.unsplash.com/photo-1604999333679-b86d54738315?auto=format&fit=crop&w=1200&q=80",
    pages: [
      `Tanggal 9 Dzulhijjah. Hari wukuf di Arafah. Inilah inti dari ibadah haji, "Al-Hajju Arafah"—Haji adalah Arafah. Jika dianalogikan, Arafah adalah simulasi kecil dari Padang Mahsyar, hari di mana seluruh umat manusia dikumpulkan di hadapan sang Khalik dengan pakaian yang sama, menanti penghakiman.\n\nSejak pagi hari, padang pasir Arafah yang biasanya sunyi berubah menjadi hamparan tenda-tenda putih sejauh mata memandang. Jutaan manusia berpakaian ihram berkumpul di bawah sengatan terik matahari gurun yang mencapai 45 derajat Celsius. Namun panas fisik itu sama sekali tidak terasa di hadapan panasnya kerinduan akan ampunan Allah.\n\nKetika matahari mulai tergelincir ke barat, menandai masuknya waktu Zhuhur, khutbah wukuf dikumandangkan. Suasana seketika berubah menjadi hening dan syahdu. Jutaan manusia keluar dari tenda mereka, berdiri menghadap kiblat, menengadahkan kedua telapak tangan ke langit.`,
      `Aku memilih duduk di atas sebuah batu besar di luar tenda, membiarkan tubuhku terpapar hangatnya angin gurun. Di tanganku, buku catatan doa telah terbuka. Satu per satu, nama kerabat yang menitipkan doa kubaca dengan perlahan. Aku membayangkan wajah-wajah mereka di tanah air—harapan mereka, kesedihan mereka, dan impian-impian mereka.\n\n"Ya Allah, kabulkanlah doa hamba-hamba-Mu yang menitipkan harapan di pundak hamba yang penuh dosa ini..." pintaku dengan suara serak.\n\nSaat waktu ashar berganti senja, atmosfer spiritual di Arafah mencapai puncaknya. Ini adalah waktu di mana pintu-pintu langit dibuka lebar-lebar dan Allah membanggakan para jamaah haji di hadapan para malaikat-Nya. Isak tangis terdengar bersahut-sahutan dari balik bebatuan dan sela-sela tenda. Pria-pria perkasa menangis layaknya anak kecil yang kehilangan arah, memohon pengampunan atas dosa-dosa masa lalu yang mengotori lembaran hidup.`,
      `Aku memandang istriku yang bersimpuh di atas sajadahnya beberapa meter dariku. Air matanya telah membasahi mukena putihnya. Kami berdua tahu, momen beberapa jam ini menentukan sisa hidup kami ke depan. Apakah kami akan kembali ke tanah air sebagai pribadi yang baru, ataukah tetap menjadi hamba yang merugi.\n\nKetika matahari benar-benar tenggelam di balik ufuk barat padang Arafah, sebuah kelegaan yang luar biasa merayap masuk ke dalam relung dada. Rasanya seolah ada beban ribuan ton yang diangkat dari atas pundak kami. Jiwa kami terasa begitu ringan, bersih, dan damai.\n\nKami mengemasi barang bawaan kami bersiap menuju Muzdalifah untuk mabit (bermalam) dan mengumpulkan batu-batu kecil. Di bawah siraman cahaya bulan sabit, kami meninggalkan padang Arafah dengan hati yang dipenuhi rasa syukur yang tak terhingga.`
    ]
  },
  {
    id: "chapter-5",
    number: 5,
    title: "Hamparan Batu di Lembah Mina",
    subtitle: "Menjemput Cahaya di Bumi Perkemahan",
    isLocked: true,
    summary: "Bab Eksklusif penutup perjalanan di Mina, melempar jumrah sebagai simbol perlawanan terhadap bisikan ego batin, dan kepulangan penuh berkah.",
    imageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80",
    pages: [
      `Mina, lembah berbatu yang terletak di antara Mekah dan Muzdalifah, menjadi persinggahan kami berikutnya selama tiga hari ke depan untuk mabit dan melempar Jumrah. Mina adalah bumi perjuangan fisik yang sesungguhnya. Di sinilah daya tahan tubuh, kesabaran mental, dan keluhuran akhlak diuji sampai ke batas maksimal.\n\nTenda kami di Mina sangat sederhana, dihuni oleh sekitar tiga puluh jamaah yang harus berbagi ruang sempit untuk tidur dan meluruskan kaki. Namun, kesempitan fisik itu justru melahirkan kebersamaan yang sangat indah. Kami saling berbagi makanan, saling memijat kaki yang bengkak, dan saling menghibur di kala lelah melanda.\n\nSetiap hari, kami berjalan kaki sejauh beberapa kilometer menyusuri terowongan-terowongan Mina yang padat menuju jembatan Jamarat untuk melemparkan kerikil-kerikil yang kami kumpulkan dari Muzdalifah ke tiga pilar batu: Ula, Wustha, dan Aqabah. Melempar jumrah bukanlah ritual kemarahan fisik kepada iblis, melainkan sebuah ikrar batin untuk melempar keluar segala sifat buruk, keserakahan, dan egoisme yang bersarang di dalam diri.`,
      `Setiap kerikil yang ku lemparkan diiringi pekikan takbir, "Allahu Akbar! Rajman lisy-syayatin wa ridhan lir-Rahman." (Allah Maha Besar! Sebagai lemparan bagi setan dan mencari ridha Allah Yang Maha Pengasih). Aku membayangkan melempar kesombonganku, kemalasanku, dan segala nafsu duniawi yang sering kali membutakan mata hatiku.\n\nDi malam terakhir di lembah Mina, aku duduk di luar tenda di bawah langit malam yang bertabur bintang tipis. Angin malam bertiup sepoi-sepoi membawa aroma debu gurun dan wewangian dari tenda-tenda tetangga. Aku menatap celengan tanah liat berbentuk Ka'bah yang kini kurasakan telah menjelma menjadi kenyataan hidup.\n\nDua belas tahun penantian, ribuan jam mengajar mengaji, dan ribuan baris kode pemrograman yang kutulis di tengah malam sepi—semuanya bermuara di sini, di bumi Mina. Air mataku menetes kembali, namun kali ini adalah air mata kepasrahan dan rasa damai yang mendalam.`,
      `Setelah menyelesaikan Nafar Tsani (meninggalkan Mina setelah tiga hari), kami kembali ke Mekah untuk melaksanakan Thawaf Ifadah dan Sa'i Haji—rukun terakhir yang menyempurnakan seluruh rangkaian ibadah haji kami. Ketika kami memotong beberapa helai rambut (tahallul) sebagai tanda berakhirnya seluruh larangan ihram, rasanya seperti dilahirkan kembali dari rahim ibu.\n\nKini, sebelum melangkah pulang ke tanah air, aku menutup bab terakhir catatan memoar ini di lobi hotel yang tenang, menatap gerbang Masjidil Haram di kejauhan. \n\nPerjalanan haji telah usai secara fisik, namun perjalanan haji yang sesungguhnya—yaitu menjaga kemabruran dalam kehidupan sehari-hari—baru saja dimulai. "Bumi Mina" akan selalu tersimpan di sudut terdalam hatiku, sebagai tempat di mana aku belajar menjadi manusia seutuhnya: hamba yang lemah di hadapan Sang Pencipta, namun dikuatkan oleh cinta dan kasih sayang-Nya yang tiada bertepi.`
    ]
  }
];
